server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: eureka-center
    appname: ×¢²áÖĞĞÄ
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

